const API = "https://dmp-private-moments.niall42643.chatgpt.site";
const app = document.querySelector("#app");
let files = [], previews = [], note = "", shareId = "", expiresAt = null;
const esc = value => String(value).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const bytes = n => n < 1e6 ? `${Math.max(1,Math.round(n/1000))} KB` : `${(n/1e6).toFixed(1)} MB`;
const shareUrl = id => `${location.origin}${location.pathname}?dmp=${id}`;

function frame(content){app.innerHTML=`<nav class="nav"><button class="brand" data-home><span class="mark">D</span><span>DMP</span></button><span class="nav-line"></span><span class="nav-copy">Made for the group chat</span><button class="price">$1 / month</button></nav>${content}<footer class="footer"><span>DMP / 2026</span><span>A smaller, better internet.</span><span>Private links · 30-day expiry</span></footer>`;document.querySelectorAll("[data-home]").forEach(x=>x.onclick=reset)}
function reset(){previews.forEach(URL.revokeObjectURL);files=[];previews=[];note="";shareId="";expiresAt=null;history.replaceState({},"",location.pathname);renderCreate()}
function renderCreate(error=""){
  const media=files.length?`<div class="media-grid ${files.length===1?'single':''}">${files.map((f,i)=>`<figure>${f.type.startsWith('video/')?`<video src="${previews[i]}" controls></video>`:`<img src="${previews[i]}" alt="Selected upload ${i+1}">`}<figcaption>${bytes(f.size)}</figcaption></figure>`).join('')}</div>`:`<div class="dropzone" id="drop"><div class="plus">+</div><h3>Drop the good stuff here</h3><p>1–10 images, or 1 video up to 2 minutes</p><button class="secondary" id="choose">Choose from device</button></div>`;
  const result=shareId?`<div class="result"><p>Your link is ready</p><div class="link-box"><span>${shareUrl(shareId)}</span><button id="copy">Copy</button></div><p class="expiry">Expires ${expiresAt.toLocaleDateString(undefined,{day:'numeric',month:'long',year:'numeric'})}</p><div class="actions"><button class="text-btn" id="share">Share now ↑</button><button class="text-btn" id="preview">Preview recipient view →</button></div></div>`:`<button class="primary" id="create" ${files.length?'':'disabled'}><span>Create private link</span><span>→</span></button>`;
  frame(`<section class="shell create"><div><p class="eyebrow">No feed. No followers. No forever.</p><h1>Share the moment.<br><em>Keep it between you.</em></h1><p class="lede">A private drop of photos or video, made to travel through the chats you already trust. Every link disappears in 30 days.</p><div class="principles"><span>Private by default</span><span>Shared by link</span><span>Gone in 30 days</span></div></div><div class="card"><div class="card-head"><div><span class="step">01</span><h2>Make a DMP</h2></div><span class="draft">PRIVATE DRAFT</span></div>${media}<input id="file" class="sr-only" type="file" accept="image/*,video/*" multiple><label class="note-label" for="note">Add a note <span>OPTIONAL</span></label><textarea id="note" maxlength="180" rows="3" placeholder="What should they know?">${esc(note)}</textarea><div class="meta"><span>${note.length}/180</span><span>Visible to anyone with the link</span></div>${error?`<p class="error" role="alert">${esc(error)}</p>`:''}${result}</div></section>`);
  const input=document.querySelector('#file');input.onchange=e=>accept([...e.target.files]);document.querySelector('#choose')?.addEventListener('click',()=>input.click());const drop=document.querySelector('#drop');if(drop){drop.ondragover=e=>{e.preventDefault();drop.classList.add('active')};drop.ondragleave=()=>drop.classList.remove('active');drop.ondrop=e=>{e.preventDefault();accept([...e.dataTransfer.files])}}document.querySelector('#note').oninput=e=>{note=e.target.value;document.querySelector('.meta span').textContent=`${note.length}/180`};document.querySelector('#create')?.addEventListener('click',createDmp);document.querySelector('#copy')?.addEventListener('click',copy);document.querySelector('#share')?.addEventListener('click',share);document.querySelector('#preview')?.addEventListener('click',()=>openDmp(shareId));
}
function accept(incoming){const imgs=incoming.filter(f=>f.type.startsWith('image/')),vids=incoming.filter(f=>f.type.startsWith('video/'));if((vids.length&&incoming.length>1)||vids.length>1||imgs.length>10||(!imgs.length&&!vids.length))return renderCreate('Choose 1–10 images or one video.');previews.forEach(URL.revokeObjectURL);files=vids.length?[vids[0]]:imgs.slice(0,10);previews=files.map(URL.createObjectURL);shareId='';renderCreate()}
async function createDmp(){const button=document.querySelector('#create');button.disabled=true;button.firstElementChild.textContent='Uploading securely…';try{const init=await fetch(`${API}/api/dmps`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({note,files:files.map(({name,type,size})=>({name,type,size}))})});const data=await init.json();if(!init.ok)throw Error(data.error||'Upload failed.');for(let i=0;i<files.length;i++){const count=Math.ceil(files[i].size/(700*1024));for(let part=0;part<count;part++){const response=await fetch(`${API}/api/uploads/${data.uploads[i].id}?dmp=${data.id}&part=${part}&final=${part===count-1?1:0}`,{method:'PUT',headers:{'Content-Type':'application/octet-stream'},body:files[i].slice(part*700*1024,(part+1)*700*1024)});if(!response.ok)throw Error('Upload was interrupted. Please try again.')}}shareId=data.id;expiresAt=new Date(data.expiresAt);history.replaceState({},'',`?dmp=${shareId}`);renderCreate()}catch(e){renderCreate(e.message||'Upload failed.')}}
async function copy(){await navigator.clipboard.writeText(shareUrl(shareId));document.querySelector('#copy').textContent='Copied'}
async function share(){navigator.share?await navigator.share({title:'A private DMP',text:note||'I made a DMP for you.',url:shareUrl(shareId)}).catch(()=>{}):copy()}
async function openDmp(id){frame(`<section class="viewer"><header class="viewer-head"><button class="brand" data-home><span class="mark">D</span><span>DMP</span></button><div><p>A private DMP</p><span>Shared with you · expires in 30 days</span></div></header><div class="state">Opening this DMP…</div></section>`);try{const response=await fetch(`${API}/api/dmps/${encodeURIComponent(id)}`,{cache:'no-store'});const d=await response.json();if(!response.ok)throw Error(d.error||'Unable to open this DMP.');frame(`<section class="viewer"><header class="viewer-head"><button class="brand" data-home><span class="mark">D</span><span>DMP</span></button><div><p>A private DMP</p><span>Shared with you · expires in 30 days</span></div></header><div class="viewer-grid ${d.media.length===1?'single':''}">${d.media.map((m,i)=>m.type.startsWith('video/')?`<video src="${m.url}" controls playsinline preload="metadata"></video>`:`<img src="${m.url}" alt="Shared moment ${i+1}">`).join('')}</div>${d.note?`<blockquote>“${esc(d.note)}”</blockquote>`:''}<footer class="viewer-footer"><span>This DMP won’t live forever · expires ${new Date(d.expiresAt).toLocaleDateString()}</span><button class="text-btn" data-home>Make your own</button></footer></section>`);document.querySelectorAll('[data-home]').forEach(x=>x.onclick=reset)}catch(e){frame(`<section class="viewer"><div class="state"><strong>This moment has passed.</strong><p>${esc(e.message)}</p><button class="primary" data-home>Make your own DMP</button></div></section>`);document.querySelectorAll('[data-home]').forEach(x=>x.onclick=reset)}}
const id=new URLSearchParams(location.search).get('dmp');id?openDmp(id):renderCreate();
